### ISSUE TITLE
getting a error when building

### ISSUE THREAD

**Issue by hazre** [axeluhl/TickChunks#5]
I did all the steps but midway I got this error:
`Picked up _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true
Applying CraftBukkit Patches
Patching with Advancement.patch
Exception in thread "main" difflib.PatchFailedException: Incorrect Chunk: the chunk content doesn't match the target
        at difflib.Chunk.verify(Chunk.java:86)
        at difflib.ChangeDelta.verify(ChangeDelta.java:78)
        at difflib.ChangeDelta.applyTo(ChangeDelta.java:44)
        at difflib.Patch.applyTo(Patch.java:43)
        at difflib.DiffUtils.patch(DiffUtils.java:70)
        at org.spigotmc.builder.Builder.main(Builder.java:477)
        at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:29)`

how do I fix this? I ran the command "java -jar BuildTools.jar --dont-update --rev 1.13.2"

**Comment by hazre** [comment]
[BuildTools.log.txt](https://github.com/axeluhl/TickChunks/files/2676612/BuildTools.log.txt)
log file if needed.

**Comment by axeluhl** [comment]
The whole thing was built for 1.12.2. I never tried it for 1.13.x. Sorry.

**Comment by hazre** [comment]
are you going to update it for 1.13.x at some point?

**Comment by axeluhl** [comment]
Not planned yet. It already took longer than I had expected to get things up and running for 1.12.2, and it never was merged into the Spigot master, so I guess this would be a never-ending maintenance battle...

**Comment by Geitenijs** [comment]
@axeluhl What about creating a PR for Paper once you have it updated for 1.13.2? They will likely accept it, which would make the user experience so much better.
