### ISSUE TITLE
Can't get it to build

### ISSUE THREAD

**Issue by fl1k** [axeluhl/TickChunks#6]
Applying CraftBukkit Patches
Patching with Advancement.patch
Exception in thread "main" difflib.PatchFailedException: Incorrect Chunk: the chunk content doesn't match the target
	at difflib.Chunk.verify(Chunk.java:86)
	at difflib.ChangeDelta.verify(ChangeDelta.java:78)
	at difflib.ChangeDelta.applyTo(ChangeDelta.java:44)
	at difflib.Patch.applyTo(Patch.java:43)
	at difflib.DiffUtils.patch(DiffUtils.java:70)
	at org.spigotmc.builder.Builder.main(Builder.java:498)
	at org.spigotmc.builder.Bootstrap.main(Bootstrap.java:40)

Here's the whole file 
[BuildTools.log.txt](https://github.com/axeluhl/TickChunks/files/2698922/BuildTools.log.txt)

**Comment by axeluhl** [comment]
Have you been trying to apply this to 1.12.2? That's the supported version.

**Comment by Tracas** [comment]
Hi
I was trying to make this (the spigot and the plug in) and I'm stuck like fl1k say, I have got the same error. So I dont know If this plug in is only valid for the BuildTools 1.12.2 instead of 1.13.2.
The other thing is in your instructions, you say:
wget "https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar"
That step is to download the latest version of BuildTools, but the patches are supposed to be for version 1.12.2.
So, I do not understand the steps well, since to apply these patches, you need version 1.12.2 of the BuildTools and you are downloading the latest version of BuildTools.
Also, if I could upload a compiled version, for the plugin, I'd be grateful.
Thanks

**Comment by axeluhl** [comment]
I haven't tried it but as far as I remember there are options to call the build tools with that let you select the version to build, so things should work with the latest build tools also when trying to build 1.12.2.  Try http://www.axel-uhl.de/TickChunks.jar

**Comment by Tracas** [comment]
[latest.log](https://github.com/axeluhl/TickChunks/files/2809979/latest.log)
Hi again!
I have uploaded the home server log that I have at home. I have configured with the plug in KeepChunks a chunk that I want to keep loaded, but putting /tickchunks keep giving error.
